### ISSUE TITLE
Question - Creating custom spans in functions

### ISSUE THREAD

**Issue by iamsurya-dev** [opentracing-contrib/java-opentracing-walkthrough#2]
I have just started to explore distributed tracing and have a question regarding this. 
I want to create a Span inside the `parseDonutInfo()` to trace the time taken to complete the function call. 
https://github.com/opentracing-contrib/java-opentracing-walkthrough/blob/master/microdonuts/src/main/java/com/otsample/api/ApiContextHandler.java#L85

In order to do that, I create a span - 
```
try (Span parseDonutsInfoSpan =
                GlobalTracer.get().buildSpan("parseDonutsInfo_span")start()) {}
```
However, this span doesn't get included along with the parent Span. It is present as a separate trace in Zipkin UI. How do I ensure that doPost function is the parentSpan of parseDonutsInfo(). 

Thanks, Let me know if you need any more details.

**Comment by jorgheymans** [comment]
AFAIU since the parent span was put as an attribute on the request in doPost (just before the call to parseDonutsInfo), you could just do this:

```
        static DonutRequest[] parseDonutsInfo(HttpServletRequest request)
            throws IOException
        {
            Span parentSpan = (Span) request.getAttribute("span");
            Span parseDonutsInfoSpan = GlobalTracer.get().buildSpan("parseDonutsInfo_span").asChildOf(parentSpan)
                .start();
          ... 
          parseDonutsInfoSpan.finish();
```

**Comment by iamsurya-dev** [comment]
Thanks for the reply @jorgheymans . My question is slightly different, though I may have not worded it properly. How do I ensure that a Span is included as a part of the common GlobalTracer without explicitly passing the parentSpan. 
 Scenario -
If I want perform a trace = `doPost() -> func1() -> func2() -> DB call -> Return`. If I were to achieve this trace, should I pass the respective parentSpan across each of these operations?

**Comment by jorgheymans** [comment]
According to https://github.com/opentracing/opentracing-java#accessing-the-tracer  you should be ok to use GlobalTracer.get().activeSpan() , and pass that in asChildOf().

**Comment by iamsurya-dev** [comment]
`<artifactId>opentracing-api</artifactId>` is not included in the pom. @bhs it'll be helpful if you can share some insight on this. Thanks!

**Comment by bhs** [comment]
@kvsurii I'm sorry for the delay, just noticed this thread via a separate search!

If adding the `opentracing-api` artifact resolves the issue here, we should just make that change. From skimming the above, I believe the problem may instead be resolved by the `activeSpan()` functionality... that way you can take advantage of TLS and save the trouble of manually passing the Span instance around.

**Comment by iamsurya-dev** [comment]
Thanks for the comment @bhs ! It looks like https://github.com/opentracing-contrib/java-opentracing-walkthrough/pull/3 is using activeSpan(). I'll also try it out from my end.
